### ISSUE TITLE
TypeError: Cannot read property 'startLine' of undefined (v0.13.0)

### ISSUE THREAD

**Issue by viceice** [prettier/plugin-xml#158]
I get the following error if i try to update to newest version

```

$ prettier "{**/*,*}.*" -u --list-different
--
1183 | [error] dir\file.xml: TypeError: Cannot read property 'startLine' of undefined
1184 | [error]     at Object.element (C:\drone\src\node_modules\@prettier\plugin-xml\src\printer.js:336:34)
1185 | [error]     at Object.genericPrint [as print] (C:\drone\src\node_modules\@prettier\plugin-xml\src\printer.js:412:30)
1186 | [error]     at callPluginPrintFunction (C:\drone\src\node_modules\prettier\index.js:14718:18)
1187 | [error]     at C:\drone\src\node_modules\prettier\index.js:14649:47
1188 | [error]     at Object.printComments (C:\drone\src\node_modules\prettier\index.js:14305:19)
1189 | [error]     at printGenerically (C:\drone\src\node_modules\prettier\index.js:14649:22)
1190 | [error]     at FastPath.call (C:\drone\src\node_modules\prettier\index.js:14441:20)
1191 | [error]     at C:\drone\src\node_modules\@prettier\plugin-xml\src\printer.js:308:27
1192 | [error]     at Array.map (<anonymous>)
1193 | [error]     at Object.element (C:\drone\src\node_modules\@prettier\plugin-xml\src\printer.js:304:19)


```

*dir\file.xml*
```yml
<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<Event>
    <Process id="XXX.Notification">

    </Process>
    <!--<Process id="XXX.Notification.Tmpl" >
        <Condition>[v:NType] == 'Tmpl'</Condition>
    </Process>-->
</Event>

```

**Comment by lboehm** [comment]
+1 I've got the same error. In my case this file content leads to the error:

```
<mvc:View controllerName="demo.controller.App" xmlns:html="http://www.w3.org/1999/xhtml" 
xmlns:mvc="sap.ui.core.mvc" 
displayBlock="true"
	xmlns="sap.m">
	<App id="app">
	</App>
</mvc:View>
```

**Comment by Tarrowren** [comment]
```xml
<!-- this is ok -->
<a>
  <b></b>
</a>

<!-- add line feed or space throws the error-->
<a>
  <b> </b>
</a>
```
