### ISSUE TITLE
[v3] printer.embed has too many parameters.

### ISSUE THREAD

**Issue by regseb** [prettier/plugin-xml#689]
## Description

The `plugin-xml` doesn't seem to be compatible with the new [Prettier V3](https://prettier.io/blog/2023/07/05/3.0.0.html#support-plugins-with-async-parsers-12748httpsgithubcomprettierprettierpull12748-by-fiskerhttpsgithubcomfisker-13211httpsgithubcomprettierprettierpull13211-by-thorn0httpsgithubcomthorn0-and-fiskerhttpsgithubcomfisker):

> Error: printer.embed has too many parameters. The API changed in Prettier v3. Please update your plugin. See https://prettier.io/docs/en/plugins.html#optional-embed

## Files

- `package.json`

  ```JSON
  {
      "name": "testcase",
      "version": "1.0.0",
      "type": "module",
      "dependencies": {
          "@prettier/plugin-xml": "2.2.0",
          "prettier": "3.0.0"
      }
  }
  ```

- `.prettierrc.js`

  ```JavaScript
  import pluginXML from "@prettier/plugin-xml";

  export default {
      plugins: [pluginXML],
  };
  ```

- `foo.xml`

  ```XML
  <foo>Bar</foo>
  ```

## To reproduce

- `npm install`
- `npx prettier foo.xml`

## Output

```
foo.xml
[error] foo.xml: Error: printer.embed has too many parameters. The API changed in Prettier v3. Please update your plugin. See https://prettier.io/docs/en/plugins.html#optional-embed
[error]     at printEmbeddedLanguages (file:///home/regseb/testcase/node_modules/prettier/index.mjs:17963:11)
[error]     at printAstToDoc (file:///home/regseb/testcase/node_modules/prettier/index.mjs:18094:9)
[error]     at async coreFormat (file:///home/regseb/testcase/node_modules/prettier/index.mjs:18405:14)
[error]     at async formatWithCursor (file:///regseb/testcase/node_modules/prettier/index.mjs:18603:14)
[error]     at async formatFiles (file:///home/regseb/testcase/node_modules/prettier/internal/cli.mjs:6778:18)
[error]     at async main (file:///home/regseb/testcase/node_modules/prettier/internal/cli.mjs:6970:5)
[error]     at async Module.run (file:///home/regseb/testcase/node_modules/prettier/internal/cli.mjs:6924:5)
```

**Comment by kddnewton** [comment]
It's compatible on the main branch, but I was waiting for v3 to be released to release this version.
