### ISSUE TITLE
Exception when formatting with prettier standalone in browser

### ISSUE THREAD

**Issue by medihack** [prettier/plugin-xml#753]
I get an exception using the below code to format some XML in the browser:

```typescript
import xmlPlugin from "@prettier/plugin-xml"
import { formatWithCursor } from "prettier/standalone"

async function formatSVG(code: string, cursorOffset: number): Promise<[string, number]> {
  const result = await formatWithCursor(code, {
    parser: "xml",
    cursorOffset,
    xmlWhitespaceSensitivity: "ignore",
    plugins: [xmlPlugin],
  })
  return [result.formatted, result.cursorOffset]
}
```

This is the thrown exception:

```
parser.js:61 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'startOffset')
    at locStart (parser.js:61:26)
    at i (standalone.mjs:39:2281)
    at o (standalone.mjs:27:4923)
    at Ot (standalone.mjs:27:5014)
    at Ot.next (<anonymous>)
    at jr (standalone.mjs:27:5105)
    at jr.next (<anonymous>)
    at wo (standalone.mjs:39:2310)
    at Jn (standalone.mjs:39:5540)
    at async Zt (standalone.mjs:44:581)
    at async formatSVG (codeFormatting.ts:39:18)
    at async onClick (EditorToolbar.tsx:126:26)
```

I use some built-in plugins that way without any problems. How do I have to use `@prettier/plugin-xml`?

**Comment by medihack** [comment]
When using just `format` and not `formatWithCursor` it works fine. Is `formatWithCursor` not supported?

**Comment by kddnewton** [comment]
This is now fixed on `main` and I'll release a new version
