### ISSUE TITLE
Bug in src/embed.js @getParser(node, opts)

### ISSUE THREAD

**Issue by shane-au-wade** [prettier/plugin-xml#810]
Stack trace

`
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at getParser (file:///Users/shane/repos/brm/node_modules/@prettier/plugin-xml/src/embed.js:56:21)
    at embed (file:///Users/shane/repos/brm/node_modules/@prettier/plugin-xml/src/embed.js:121:18)
    at recurse (file:///Users/shane/repos/brm/node_modules/prettier/index.mjs:22194:20)
    at AstPath.each (file:///Users/shane/repos/brm/node_modules/prettier/index.mjs:20791:9)
    at recurse (file:///Users/shane/repos/brm/node_modules/prettier/index.mjs:22189:16)
    at AstPath.call (file:///Users/shane/repos/brm/node_modules/prettier/index.mjs:20753:14)
    at recurse (file:///Users/shane/repos/brm/node_modules/prettier/index.mjs:22191:16)
    at AstPath.each (file:///Users/shane/repos/brm/node_modules/prettier/index.mjs:20791:9)
    at recurse (file:///Users/shane/repos/brm/node_modules/prettier/index.mjs:22189:16)
    at AstPath.call (file:///Users/shane/repos/brm/node_modules/prettier/index.mjs:20753:14)
`

console.log(node)

![Screenshot 2024-08-12 at 11 23 49 AM](https://github.com/user-attachments/assets/4670fb97-1e51-4fc2-a6b0-0d1393f3358f)

and the function is attempting to destructured some properties that don't exist

`
const { Name, attribute } = node;
let parser = Name.toLowerCase();
` 

thus we get the undefined TypeError

details of my machine

![Screenshot 2024-08-12 at 11 27 04 AM](https://github.com/user-attachments/assets/ab2ea0a7-a2e4-466b-832b-d78113061d76)

prettier config

`{
  "trailingComma": "es5",
  "tabWidth": 2,
  "printWidth": 120,
  "semi": false,
  "singleQuote": false,

  "language": "postgresql",
  "keywordCase": "upper",

  "embeddedSqlTags": ["db.sql", "sql"],
  "embeddedSqlComments": ["db.sql", "sql"],

  "overrides": [
    {
      "files": ["*.md", "*.y?(a)ml"],
      "options": {
        "tabWidth": 2
      }
    }
  ],

  "plugins": ["prettier-plugin-embed", "prettier-plugin-sql", "@prettier/plugin-xml"]
}
`

command to reproduce

`
npx prettier --check . --log-level warn
`

**Comment by shane-au-wade** [comment]
I tried to fix this up, but I don't have much context of the upstream/downstream code.
