### ISSUE TITLE
Crashes while formatting NativeScript XML

### ISSUE THREAD

**Issue by FunnyGhost** [prettier/plugin-xml#96]
NativeScript uses .xml files so I thought I would use prettier-xml for auto-formatting with VsCode.

XML file example:
![Screenshot 2020-07-03 at 12 26 42](https://user-images.githubusercontent.com/6450559/86460319-75bec700-bd28-11ea-8a5e-3f3484ad1025.png)

"@prettier/plugin-xml": "0.7.2",
"prettier": "1.19.1".

It throws:
"Error: Error parsing XML
	at Object.parse (/Users/utukku/SnappCar Projects/frontend-app/node_modules/@prettier/plugin-xml/src/parse.js:7:11)
	at Object.parse (/Users/utukku/SnappCar Projects/frontend-app/node_modules/prettier/index.js:9739:19)
	at coreFormat (/Users/utukku/SnappCar Projects/frontend-app/node_modules/prettier/index.js:13252:23)
	at format (/Users/utukku/SnappCar Projects/frontend-app/node_modules/prettier/index.js:13510:73)
	at formatWithCursor (/Users/utukku/SnappCar Projects/frontend-app/node_modules/prettier/index.js:13526:12)
	at /Users/utukku/SnappCar Projects/frontend-app/node_modules/prettier/index.js:44207:15
	at Object.format (/Users/utukku/SnappCar Projects/frontend-app/node_modules/prettier/index.js:44226:12)
	at t.default.<anonymous> (/Users/utukku/.vscode/extensions/esbenp.prettier-vscode-5.1.3/dist/extension.js:1:58387)
	at Generator.next (<anonymous>)
	at s (/Users/utukku/.vscode/extensions/esbenp.prettier-vscode-5.1.3/dist/extension.js:1:53305)"

**Comment by kddeisz** [comment]
Sorry the error message here could definitely be improved. It's breaking because according to the XML spec you can only have one root node. If you wrap those nodes together into one root node it should function properly.
